### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by GregMage** [djculex/xoopssecure#5]
Erreur: Error: Class "XoopsModules/Xoopssecure/Utility" not found dans le fichier /modules/xoopsSecure/include/install.php ligne 27

Xoops 2.5.11 (most updated version).
PHP 8.1.13

**Comment by djculex** [comment]
I can't reproduce this error ?

Tried with fresh install in local & hosted.

Local fresh 1
Xoops 2.5.11 beta 2
Php 8.1.12 

local 2
xoops 2.5.10
php 8.1.12

Hosted 
Xoops XOOPS 2.5.11-Beta2
php 8.0.27

Both cases it installs without errors. 

Maybe some fixes back, try fresh download from frontpage.

**Comment by GregMage** [comment]
The problem comes from the "preloads/autoloader.php" file. I think the main problem comes from the name of the module folder (the capital letter), in your code you don't put a capital letter in the paths. On some systems it works but on others not (windows). This condition is activated from the first launch and it does not work:
`
            if (0 !== \strncmp($prefix, $class, $len)) {
				echo '<br>problème';
                return;
            }
`

**Comment by GregMage** [comment]
thank you
