### ISSUE TITLE
Undefined constant

### ISSUE THREAD

**Issue by GregMage** [djculex/xoopssecure#6]
Erreur: Error: Undefined constant "XoopsModules/Xoopssecure/_AM_XOOPSSECURE_POSTMAXSIZE" dans le fichier /modules/xoopssecure/class/mech.php ligne 247

**Comment by djculex** [comment]
fixed in #7cc5d33b19129f0d3e28bb558e010e3d43b0b7fb

**Comment by djculex** [comment]
fixed in 7cc5d33b19129f0d3e28bb558e010e3d43b0b7fb and 7464ee1b194609c97504389f3a9760250d6b74a8
