### ISSUE TITLE
Call to undefined function XoopsModules\Xoopssecure

### ISSUE THREAD

**Issue by GregMage** [djculex/xoopssecure#7]
in "/modules/xoopssecure/admin/serverhome.php"

Erreur: Error: Call to undefined function XoopsModules/Xoopssecure/str_contains() dans le fichier /modules/xoopssecure/class/Db.php ligne 456

To fix, you must be in php 8! It is therefore necessary to modify the minimum version of php (currently 7.0) and put 8.0.

**Comment by djculex** [comment]
fixed in 28de50c2773a8a89299d75e4d0d121336780a403
